# Generated by Django 4.0.6 on 2022-09-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0005_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
