# Generated by Django 4.1 on 2022-09-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0006_productos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
