# Generated by Django 4.1 on 2022-09-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0007_remove_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
