# Generated by Django 4.1 on 2022-09-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0008_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
