# Generated by Django 4.1 on 2022-09-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0007_alter_productos_imagen'),
        ('WebPage', '0009_alter_productos_imagen'),
    ]

    operations = [
    ]
