# Generated by Django 4.0.6 on 2022-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0010_merge_20220903_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Stock',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='info',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
