# Generated by Django 4.0.6 on 2022-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0011_productos_stock_productos_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha',
            field=models.DateField(blank=True, db_column='fecha', null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='info',
            field=models.CharField(default=0, max_length=1500),
        ),
    ]
