# Generated by Django 4.0.6 on 2022-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='fecha',
            field=models.DateField(blank=True, db_column='fecha', null=True),
        ),
    ]
