# Generated by Django 4.1 on 2022-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0003_alter_mensajes_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
